server:
  port: 9000

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/
     
spring:
  cloud:
    gateway:
      mvc:
        routes:
#        - id: USER-MS
#          uri: lb://USER-MS
#          predicates:
#          - Path=/user/**
#        - id: CONTACT-MS
#          uri: lb://CONTACT-MS
#          predicates:
#          - Path=/contact/**
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
          - Path=/user/**
        - id: CAB-SERVICE
          uri: lb://CAB-SERVICE
          predicates:
          - Path=/cab/**