server:
  port: 9002
     
spring:
  config:
    import:
    - configserver:http://localhost:8085
  application:
    name: USER-SERVICE
    
  security:
    oauth2:
      client:
        registration:
          google:
           client-name: google
           client-id: 838259786920-hu15urflc4stb871bdq4vk3enddmjei0.apps.googleusercontent.com 
           client-secret: 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